class MainRun{
	public static void main(String[]args){
		Animal.sleep();
		Animal.eat();
		Animal animal=new Animal();
		animal.breathe();
		animal.move();
		Dog.sleep();
		Dog.eat();
		Dog dog=new Dog();
		dog.breathe();
		dog.move();
		Animal A=new Dog();
		A.makeSound();
		A.play();
		A.drink();
		System.out.println("-----------------");
		
		Instrument.tune();
		Instrument.clean();
		Instrument instru=new Instrument();
		instru.store();
		instru.repair();
		Guitar.tune();
		Guitar.clean();
		Guitar guitar=new Guitar();
		guitar.store();
		guitar.repair();
		Instrument ins=new Guitar();
		ins.play();
		ins.testSound();
		ins.displayInfo();
	    System.out.println("-----------------");
		
		Artist.startWork();
		Artist.finishWork();
		Artist artist= new Artist();
		artist.display();
		artist.sign();
		Painter.startWork();
		Painter.finishWork();
		Painter painter=new Painter();
		painter.display();
		painter.sign();
		Artist pain=new Painter();
		pain.draw();
		pain.color();
		pain.paint();
		System.out.println("-----------------");
		
		Robot.start();
	    Robot.shutdown();
		Robot robot=new Robot();
		robot.speak();
		robot.charge();
		CleaningRobot.start();
		CleaningRobot.shutdown();
		CleaningRobot cleaning=new CleaningRobot();
		cleaning.speak();
		cleaning.charge();
		Robot R=new CleaningRobot();
		R.move();
		R.work();
		R.recharge();
		System.out.println("-----------------");
		
		Library.openLibrary();
		Library.closeLibrary();
		Library library=new Library();
		library.organizeBooks();
		library.fineCollection();
		DigitalLibrary.openLibrary();
		DigitalLibrary.closeLibrary();
		DigitalLibrary digital=new DigitalLibrary();
		digital.organizeBooks();
		digital.fineCollection();
		Library D=new DigitalLibrary();
		D.issueBook();
		D.returnBook();
		D.bookNumber();
		System.out.println("-----------------");
		
		Bank.openAccount();
		Bank.closeAccount();
		Bank bank=new Bank();
		bank.deposit();
		bank.issueCard();
		ATM.openAccount();
		ATM.closeAccount();
		ATM account=new ATM();
		account.deposit();
		account.issueCard();
		Bank B=new ATM();
		B.withdraw();
		B.checkBalance();
		B.document();
		System.out.println("-----------------");
		
		Movie.start();
		Movie.end();
		Movie movie=new Movie();
		movie.showCredits();
		movie.pause();
		ActionMovie.start();
		ActionMovie.end();
		ActionMovie action=new ActionMovie();
		action.showCredits();
		action.pause();
		Movie mov=new ActionMovie();
		mov.playScene();
		mov.rateMovie();
		mov.time();
		System.out.println("-----------------");
		
		Hospital.open();
		Hospital.close();
		Hospital hospital=new Hospital();
		hospital.dischargePatient();
		hospital.operate();
		Clinic.open();
		Clinic.close();
		Clinic clinic=new Clinic();
		clinic.dischargePatient();
		clinic.operate();
		Hospital hos=new Clinic();
		hos.admitPatient();
		hos.maintainRecords();
		hos.records();
		System.out.println("-----------------");
		
		Music.playMusic();
		Music.stopMusic();
		Music music=new Music();
		music.mix();
		music.listen();
		Song.playMusic();
		Song.stopMusic();
		Song song=new Song();
		song.mix();
		song.listen();
		Music son=new Song();
		son.record();
		son.publish();
		son.volume();
		System.out.println("-----------------");
		
		Game.load();
		Game.quit();
		Game game=new Game();
		game.pause();
		game.restart();
		Chess.load();
		Chess.quit();
		Chess chess=new Chess();
		chess.pause();
		chess.restart();
		Game ches=new Chess();
		ches.play();
		ches.score();
		ches.start();
		System.out.println("-----------------");
		
		Employe.joinOffice();
		Employe.logout();
		Employe employe=new Employe();
		employe.attendMeeting();
		employe.takeBreak();
		Manager.joinOffice();
		Manager.logout();
		Manager manager=new Manager();
		manager.attendMeeting();
		manager.takeBreak();
		Employe emp=new Manager();
		emp.work();
		emp.submitReport();
		emp.login();
		System.out.println("-----------------");
		
		Teacher.enterClass();
		Teacher.markAttendance();
		Teacher teacher=new Teacher();
		teacher.checkPapers();
		teacher.evaluateStudents();
		MathTeacher.enterClass();
		MathTeacher.markAttendance();
		MathTeacher math=new MathTeacher();
		math.checkPapers();
		math.evaluateStudents();
		Teacher tea=new MathTeacher();
		tea.giveHomework();
		tea.teach();
		tea.record();
		System.out.println("-----------------");
		
		Sports1.startGame();
		Sports1.endGame();
		Sports1 sport=new Sports1();
		sport.practice();
		sport.award();
		Cricket.startGame();
		Cricket.endGame();
		Cricket cricket=new Cricket();
		cricket.practice();
		cricket.award();
		Sports1 sp=new Cricket();
		sp.play();
		sp.score();
		sp.match();
		System.out.println("-----------------");
		
		Plant.water();
		Plant.fertilize();
		Plant plant=new Plant();
		plant.photosynthesis();
		plant.shedLeaves();
		Flower.water();
		Flower.fertilize();
		Flower flower=new Flower();
		flower.photosynthesis();
		flower.shedLeaves();
		Plant pl=new Flower();
		pl.grow();
		pl.bloom();
		pl.color();
		System.out.println("-----------------");
		
		Furniture.make();
		Furniture.polish();
		Furniture furniture=new Furniture();
		furniture.pack();
		furniture.deliver();
		Chair.make();
		Chair.polish();
		Chair chair=new Chair();
		chair.pack();
		chair.deliver();
		Furniture furn=new Chair();
		furn.assemble();
		furn.testDurability();
		furn.time();
		System.out.println("-----------------");
		
		Food.cook();
		Food.pack();
		Food food=new Food();
		food.garnish();
		food.store();
		Pizza.cook();
		Pizza.pack();
		Pizza pizza=new Pizza();
		pizza.garnish();
		pizza.store();
		Food pi=new Pizza();
		pi.serve();
		pi.taste();
		pi.shape();
		System.out.println("-----------------");
		
		Computer.boot();
		Computer.shutdown();
		Computer computer=new Computer();
		computer.compile();
		computer.display();
		HPLaptop.boot();
		HPLaptop.shutdown();
		HPLaptop hp=new HPLaptop();
		hp.compile();
		hp.display();
		Computer laptop=new HPLaptop();
		laptop.runProgram();
		laptop.connectWifi();
		laptop.start();
		System.out.println("-----------------");
		
		Appliance.plugIn();
		Appliance.unplug();
		Appliance appliance=new Appliance();
		appliance.stop();
		appliance.repair();
		WashingMachine.plugIn();
		WashingMachine.unplug();
		WashingMachine washing=new WashingMachine();
		washing.stop();
		washing.repair();
		Appliance mach=new WashingMachine();
		mach.start();
		mach.clean();
		mach.powerOn();
		System.out.println("-----------------");
		
		Device.powerOn();
		Device.powerOff();
		Device device=new Device();
		device.operate();
		device.reset();
		Mobile.powerOn();
		Mobile.powerOff();
		Mobile mobile=new Mobile();
		mobile.operate();
		mobile.reset();
		Device dev=new Mobile();
		dev.charge();
		dev.update();
		dev.delete();
		System.out.println("-----------------");
		
		Vehicle.start();
		Vehicle.stop();
		Vehicle vehicle=new Vehicle();
	    vehicle.fuel();
		vehicle.checkEngine();
		Car.start();
		Car.stop();
		Car car=new Car();
		car.fuel();
		car.checkEngine();
		Vehicle veh=new Car();
		veh.wash();
		veh.testDrive();
		veh.color();
		System.out.println("-----------------");
		
	}
}
		